version: "3.9"
services:
  web:
    build:
      context: ./web
    image: "edenfenster/sudoku_server"
    ports:
      - "5000:5000"
    volumes:
      - .:/sudoku_server
    container_name: sudoku_web_1
  processor:
    build:
      context: ./processor
    image: "edenfenster/sudoku_processor"
    ports:
      - "8000:8000"
    volumes:
      - .:/sudoku_processor
    container_name: sudoku_processor_1
    depends_on:
      - web
