version: "3.9"
services:
  web:
    depends_on:
      - processor
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5000:5000"
    expose:
      - 5000
    container_name: sudoku_web
    hostname: sudoku_web
#    networks:
#      - my_network




  processor:
    build:
      context: .
      dockerfile: processor/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    container_name: sudoku_processor
    hostname: sudoku_processor
#    networks:
#      - my_network

  database:
    volumes:
      - .sudoku_database_directory/database:/our_database
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    container_name: sudoku_database
    hostname: sudoku_database

  query:
    build:
      context: .
      dockerfile: query/Dockerfile
    ports:
      - "1000:1000"
    expose:
      - 1000
    container_name: sudoku_query
    hostname: sudoku_query

networks:
  my_network:
    name: connect
    driver: bridge
    ipam:
      config:
        - gateway: 10.0.2.15


