version: "3.9"
services:
  web:
    depends_on:
      - processor
    build:
      dockerfile: web/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/sudoku_web
    container_name: sudoku_web_1
    networks:
      sudoku_network:
        - ipv4_address: 172.23.0.2

  processor:
    build:
      dockerfile: processor/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/sudoku_processor
    container_name: sudoku_processor_1
    networks:
      sudoku_network:
        - ipv4_address: 172.23.0.3

networks:
  sudoku_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.23.0.0/16
         gateway: 172.23.0.1

