version: "3.9"
services:
  web:
    depends_on:
      - processor
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5000:5000"
    container_name: sudoku_web
    hostname: sudoku_web
    networks:
      sudoku_network:
        ipv4_address: 172.23.0.2


  processor:
    volumes:
      - /var/lib/docker/containers/48d0d49e4082814e0e6601472e3cff2c6b28bd610620a73068a97c7357697f38/48d0d49e4082814e0e6601472e3cff2c6b28bd610620a73068a97c7357697f38-json
    build:
      context: .
      dockerfile: processor/Dockerfile
    ports:
      - "8000:5000"
    container_name: sudoku_processor
    hostname: sudoku_processor
    networks:
      sudoku_network:
        ipv4_address: 172.23.0.3


networks:
  sudoku_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.23.0.0/16

