version: "3.9"
services:
  web:
    depends_on:
      - processor
    build:
      context: ./web
    ports:
      - "5000:5000"
    volumes:
      - .:/sudoku_server
    container_name: sudoku_web_1
    networks:
      - sudoku_network
  processor:
    build:
      context: ./processor
    ports:
      - "8000:8000"
    volumes:
      - .:/sudoku_processor
    container_name: sudoku_processor_1
    networks:
     - sudoku_network
networks:
  sudoku_network:
    external: true

