version: "3.9"
services:
  web:
    build: .
    image: "localhost:5000/sudoku_server"
    ports:
      - "5000:5000"
    volumes:
      - .:/sudoku_server
      - logvolume01:/var/log
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"
volumes:
  logvolume01: { }