version: "3.9"
services:
  web:
    build: .
    image: "edenfenster/sudoku_server"
    ports:
      - "5000:5000"
    volumes:
      - /sudoku-api:/sudoku-api
    links:
      - db:mongodb
    container_name: sudokuapi_web_1
    depends_on:
      - db
  db:
    image: mongo
    container_name: sudokuapi_db_1
